# Generated by Django 5.1 on 2024-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Короткое описание слайдера')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на запись или новость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включить слайдер на главную')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('class_css', models.CharField(blank=True, max_length=255, verbose_name='Класс для css')),
                ('title_btn', models.CharField(default='Перейти', max_length=255, verbose_name='Название кнопки')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL-на всякий')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Изображение большое')),
                ('image_mobile', models.ImageField(blank=True, upload_to='sliders/', verbose_name='Изображение на мобильном')),
                ('header_type', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2')], default='h2', max_length=2, verbose_name='Выбрать тип заголовка (H1 должен быть один)')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
