# Generated by Django 5.1 on 2024-08-26 08:33

import config_site.utils
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Введите название сайта которе будет отображаться в письмах и тд', max_length=255, null=True, verbose_name='Название сайта')),
                ('phone_number', models.CharField(blank=True, help_text='Телефонный номер, отображаемый на сайте', max_length=18, null=True, verbose_name='Телефонный номер')),
                ('phone_url', models.CharField(blank=True, help_text='Телефонный номер, ссылка, формат: +73822908070', max_length=15, null=True, verbose_name='Телефон ссылка')),
                ('phone_number_two', models.CharField(blank=True, help_text='Телефонный номер, отображаемый на сайте', max_length=18, null=True, verbose_name='Телефонный номер - 2')),
                ('phone_two_url', models.CharField(blank=True, help_text='Телефонный номер, ссылка, формат: +73822908070', max_length=15, null=True, verbose_name='Телефон ссылка - 2')),
                ('address', models.CharField(blank=True, help_text='Адрес вашей компании или организации', max_length=255, null=True, verbose_name='Адрес')),
                ('town', models.CharField(blank=True, help_text='Город вашей компании или организации', max_length=255, null=True, verbose_name='Город')),
                ('postal_code', models.IntegerField(blank=True, help_text='Индекс вашей компании или организации', null=True, verbose_name='Индекс')),
                ('email', models.EmailField(blank=True, help_text='Email, на который будут приходить сообщения с сайта', max_length=254, null=True, verbose_name='Email')),
                ('email_site', models.EmailField(blank=True, help_text='Email, который отображается на сайте', max_length=254, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, help_text='Изображение логотипа вашей компании или организации', null=True, upload_to='media/', verbose_name='Логотип')),
                ('logo_two', models.ImageField(blank=True, help_text='Изображение логотипа вашей компании или организации', null=True, upload_to='media/', verbose_name='Логотип дополнительный')),
                ('telegram', models.CharField(blank=True, help_text='https://t.me/+88009005010', max_length=255, null=True, verbose_name='телеграм ссылка')),
                ('telegram_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='телеграм иконка')),
                ('whatsapp', models.CharField(blank=True, help_text='https://wa.me/79521828125', max_length=255, null=True, verbose_name='ватсап ссылка')),
                ('whatsapp_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='ватсап иконка')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='инстаграм ссылка')),
                ('instagram_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='инстаграм иконка')),
                ('vk', models.CharField(blank=True, help_text='https://vk.com/account', max_length=255, null=True, verbose_name='вк ссылка')),
                ('vk_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='вк иконка')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='фэйсбук ссылка')),
                ('facebook_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='фэйбук иконка')),
                ('other', models.CharField(blank=True, max_length=255, null=True, verbose_name='другая ссылка')),
                ('other_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='другая иконка')),
                ('random', models.CharField(blank=True, max_length=255, null=True, verbose_name='другая-2 ссылка')),
                ('random_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='другая-2 иконка')),
                ('cache', models.IntegerField(blank=True, default=0, help_text='Указать число в секундах', verbose_name='Кеширование')),
                ('placeholder', models.ImageField(blank=True, help_text='Изображение Заглушка вашей компании', null=True, upload_to='media/', verbose_name='Заглушка')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Config_seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('meta_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Короткое описание')),
                ('reviews_meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title отзывы')),
                ('reviews_meta_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='meta_description отзывы')),
                ('og_img', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='главное изо для OG')),
                ('favicon', models.ImageField(blank=True, help_text='формат PNG размер 512х512', null=True, upload_to=config_site.utils.favicon_upload_to, verbose_name='фавикон')),
                ('yandex_id', models.IntegerField(default=0, verbose_name='Номер счетчика яндекс метрика')),
                ('yandex_webvisor', models.BooleanField(default=False, verbose_name='Включить вебвизор яндекс')),
            ],
            options={
                'verbose_name': 'Настройки seo',
                'verbose_name_plural': 'Настройки seo',
            },
        ),
    ]
