# Generated by Django 5.1 on 2024-08-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_seo',
            name='basket_meta_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='meta_description корзина'),
        ),
        migrations.AddField(
            model_name='config_seo',
            name='basket_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Корзина отзывы'),
        ),
        migrations.AddField(
            model_name='config_seo',
            name='catalog_meta_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='meta_description catalog'),
        ),
        migrations.AddField(
            model_name='config_seo',
            name='catalog_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Catalog отзывы'),
        ),
        migrations.AddField(
            model_name='config_seo',
            name='portfolio_meta_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='meta_description корзина'),
        ),
        migrations.AddField(
            model_name='config_seo',
            name='portfolio_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Корзина отзывы'),
        ),
    ]
