# Generated by Django 5.1 on 2024-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0002_config_seo_basket_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='site_name',
            field=models.CharField(blank=True, help_text='Введите название сайта которе будет отображаться в письмах', max_length=255, null=True, verbose_name='Название сайта'),
        ),
    ]
