# Generated by Django 5.1 on 2024-08-26 08:33

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import main.models
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banner', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image_catalog', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение в каталоге')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Будет показано в каталоге', null=True, verbose_name='Описание')),
                ('content_ckeditor', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
            bases=(models.Model, main.models.MetaTagsMixin),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение портфолио',
                'verbose_name_plural': 'Изображения портфолио',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('template', models.CharField(choices=[('template', 'Шаблон основной'), ('template_1', 'Шаблон - 1'), ('template_2', 'Шаблон - 2')], default='template', max_length=15, verbose_name='Шаблон')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_menu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в меню')),
                ('title_catalog', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в каталоге')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('content_ckeditor', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image_catalog', models.ImageField(blank=True, null=True, upload_to='catalog_images/', verbose_name='Изображение в каталоге')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Популярность')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена')),
                ('weight_unit', models.CharField(choices=[('th', 'шт'), ('gr', 'гр'), ('m', 'm2')], default='th', max_length=2)),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показывать на гл. странице')),
                ('order_on_homepage', models.PositiveIntegerField(default=0, verbose_name='Порядок на главной странице')),
                ('order_is_menu', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
            bases=(models.Model, main.models.MetaTagsMixin),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='sales', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Цена')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='% скидки')),
                ('text_price', models.CharField(blank=True, help_text='к примеру: м²', max_length=255, null=True, verbose_name='Единица измерения')),
                ('weight_unit', models.CharField(choices=[('th', 'шт'), ('gr', 'гр'), ('m', 'm2')], default='th', max_length=2, verbose_name='Единица измерения')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на запись или новость')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('template', models.CharField(choices=[('template', 'Шаблон основной'), ('template_1', 'Шаблон - 1'), ('template_2', 'Шаблон - 2')], default='template', max_length=15, verbose_name='Шаблон')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_menu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в меню')),
                ('title_catalog', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в каталоге')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('content_ckeditor', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image_catalog', models.ImageField(blank=True, null=True, upload_to='catalog_images/', verbose_name='Изображение в каталоге')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('order_on_homepage', models.PositiveIntegerField(default=0, verbose_name='Порядок на главной странице')),
                ('order_is_menu', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('image_placeholder', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение заглушка')),
                ('image_catalog_temp', models.ImageField(blank=True, help_text='оно будет показываться пока не появиться основное', null=True, upload_to='temp_images/', verbose_name='Изображение в каталоге временное')),
                ('is_menu', models.BooleanField(default=False, verbose_name='Показывать в вверхнем меню')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('content_blocks', models.ManyToManyField(blank=True, to='main.contentblock', verbose_name='Блоки контента')),
                ('image_blocks', models.ManyToManyField(blank=True, to='main.imageblock', verbose_name='Изображения записи или страницы')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banner.slider', verbose_name='Слайдер на странице')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['order_on_homepage'],
            },
            bases=(models.Model, main.models.MetaTagsMixin),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Изображение категории',
                'verbose_name_plural': 'Изображения категории',
            },
        ),
    ]
