# Generated by Django 5.1 on 2024-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='blog',
            field=models.BooleanField(default=False, verbose_name='Блог'),
        ),
    ]
